from Controller.Grafo import Grafo
from Controller.Animacion import animacion
""" G.ingresarVertice('A')
G.ingresarVertice('B')
G.ingresarVertice('C')
G.ingresarVertice('D')
G.ingresarVertice('E')
G.ingresarVertice('F')
G.ingresarVertice('G')

G.ingresarArista('A', 'D', 5)
G.ingresarArista('D', 'A', 5)
G.ingresarArista('A', 'B', 7)
G.ingresarArista('B', 'A', 7)
G.ingresarArista('D', 'B', 9)
G.ingresarArista('B', 'D', 9)
G.ingresarArista('B', 'C', 8)
G.ingresarArista('C', 'B', 8)
G.ingresarArista('B', 'E', 7)
G.ingresarArista('E', 'B', 7)
G.ingresarArista('C', 'E', 5)
G.ingresarArista('E', 'C', 5)
G.ingresarArista('D', 'E', 15)
G.ingresarArista('E', 'D', 15)
G.ingresarArista('D', 'F', 6)
G.ingresarArista('F', 'D', 6)
G.ingresarArista('F', 'E', 8)
G.ingresarArista('E', 'F', 8)
G.ingresarArista('F', 'G', 11)
G.ingresarArista('G', 'F', 11)
G.ingresarArista('E', 'G', 9)
G.ingresarArista('G', 'E', 9) """

if __name__ == "__main__":
    G = Grafo()
    G.cargarRedInicial("../Data/redInicial.json")
    G.imprimirVertice()
    G.separador()
    G.imprimirArista()
    G.separador()
    G.imprimirListaAdyacentes()
    G.separador()
    G.getPozos()
    G.separador()
    G.getFuentes()
    G.separador()
    G.fuerteConexo()
    G.separador()
    G.separador()
    #G.Boruvka()
    G.Kruskal()


    #G.caminoMasCorto("Silvestre", "Coyote")
    la_animacion = animacion(G)
    la_animacion.ejecutar()

# G.profundidad(1)
# G.separador()
# print(G.getListaVisitados())
# G.separador()
# G.amplitud(1)
# print(G.amplitud(1))
